name: PR Validation
run-name: PR Validation executed by @${{ github.actor }}
on: pull_request
jobs:

  CHECK-UnitTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5

      - run: ./gradlew elog:testDebugUnitTest

